# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RIHSOb5eQMJGcH8hSmkUic9whz8aIEcx
"""

# ============================================================
# Fraud Detection - GridSearch-Optimized Models + Hard Voting Ensemble
#
# Three classifiers (Decision Tree, Random Forest, XGBoost) tuned via
# GridSearchCV, then combined into a Hard Voting ensemble. The core
# imbalance-handling choices (class_weight='balanced' for RF,
# scale_pos_weight for XGBoost) are kept fixed since those are
# deliberate design decisions, not something to search over; the grid
# tunes capacity/regularization parameters (depth, leaf size, learning
# rate, subsampling, etc.) around them.
#
# All models and grid-search results are cached to Google Drive —
# rerunning this script will not retrain anything already saved.
# ============================================================

# Install packages (Run once in Google Colab)
!pip install -q xgboost imbalanced-learn

# ============================================================
# Import Libraries
# ============================================================

import pandas as pd
import numpy as np
import joblib
import os

from google.colab import drive
drive.mount('/content/drive')

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from xgboost import XGBClassifier

from imblearn.over_sampling import SMOTE

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    make_scorer,
    fbeta_score,
    classification_report,
    confusion_matrix
)

# ============================================================
# Model caching — saves every trained model / grid-search result
# to Google Drive. Includes a feature-schema check: a cached model
# trained on a different feature set than the current run produces
# is discarded and refit automatically, rather than crashing at
# predict() time with a stale, mismatched model.
# ============================================================

MODEL_DIR = "/content/drive/MyDrive/cvel_model_cache"
os.makedirs(MODEL_DIR, exist_ok=True)

def load_or_fit(path, fit_fn, expected_n_features=None):
    if os.path.exists(path):
        cached = joblib.load(path)
        if expected_n_features is not None and hasattr(cached, "n_features_in_"):
            if cached.n_features_in_ != expected_n_features:
                print(f"  [STALE CACHE] {os.path.basename(path)} was trained on "
                      f"{cached.n_features_in_} features, current run has "
                      f"{expected_n_features}. Discarding and refitting...")
                os.remove(path)
            else:
                print(f"  [CACHE HIT] Loaded {os.path.basename(path)}")
                return cached
        else:
            print(f"  [CACHE HIT] Loaded {os.path.basename(path)}")
            return cached

    print(f"  [CACHE MISS] Fitting and saving {os.path.basename(path)}...")
    result = fit_fn()
    joblib.dump(result, path)
    return result

# ============================================================
# Load Dataset
# ============================================================

df = pd.read_csv(
    "/content/drive/MyDrive/PS_20174392719_1491204439457_log.csv"
)

print(df.head())
print(df.shape)




# ===== SECTION 3: Leak-Free Feature Engineering ===============================
FEAT_CKPT = "df_features_v4.pkl"

def engineer_features(data: pd.DataFrame) -> pd.DataFrame:
    data = data.copy()
    data["amount_to_orig_balance"] = data["amount"] / (data["oldbalanceOrg"] + 1.0)
    data["amount_to_dest_balance"] = data["amount"] / (data["oldbalanceDest"] + 1.0)

    orig_is_c = data["nameOrig"].str.startswith("C")
    dest_is_c = data["nameDest"].str.startswith("C")

    data["type_variant"] = np.select(
        [orig_is_c & dest_is_c, orig_is_c & ~dest_is_c, ~orig_is_c & dest_is_c],
        ["CC", "CM", "MC"],
        default="MM"
    )
    return data

if exists(FEAT_CKPT):
    print("Loading feature-engineered cache...")
    df = pd.read_pickle(ckpt_path(FEAT_CKPT))
else:
    print("Engineering features...")
    df = engineer_features(df)
    df.to_pickle(ckpt_path(FEAT_CKPT))
    print("Feature engineering complete.")


# ===== SECTION 4: Encoding, Split & Feature Scaling ===========================
SPLIT_CKPT = "split_scaled_v4.pkl"
TARGET = "isFraud"
DROP_COLS = ["isFraud", "isFlaggedFraud", "nameOrig", "nameDest"]
CAT_COLS = ["type", "type_variant"]

if exists(SPLIT_CKPT):
    print("Loading preprocessed split data...")
    cache = joblib.load(ckpt_path(SPLIT_CKPT))
    X_train = cache["X_train"]
    X_test = cache["X_test"]
    y_train = cache["y_train"]
    y_test = cache["y_test"]
    scaler = cache["scaler"]
    feature_columns = cache["feature_columns"]
    numeric_cols = cache["numeric_cols"]
    cat_columns_encoded = cache["cat_columns_encoded"]
else:
    print("Running stratified split and one-hot encoding...")
    y = df[TARGET].astype(int)
    X = df.drop(columns=DROP_COLS)

    X_train_raw, X_test_raw, y_train, y_test = train_test_split(
        X, y, test_size=0.25, stratify=y, random_state=RANDOM_STATE
    )

    X_train_cat = pd.get_dummies(X_train_raw[CAT_COLS], drop_first=True, dtype=np.float32)
    X_test_cat = pd.get_dummies(X_test_raw[CAT_COLS], drop_first=True, dtype=np.float32)
    X_test_cat = X_test_cat.reindex(columns=X_train_cat.columns, fill_value=0.0)

    cat_columns_encoded = X_train_cat.columns.tolist()
    numeric_cols = [c for c in X_train_raw.columns if c not in CAT_COLS]

    scaler = StandardScaler()
    X_train_num = pd.DataFrame(
        scaler.fit_transform(X_train_raw[numeric_cols]),
        columns=numeric_cols,
        index=X_train_raw.index
    )
    X_test_num = pd.DataFrame(
        scaler.transform(X_test_raw[numeric_cols]),
        columns=numeric_cols,
        index=X_test_raw.index
    )

    X_train = pd.concat([X_train_num, X_train_cat], axis=1)
    X_test = pd.concat([X_test_num, X_test_cat], axis=1)
    feature_columns = X_train.columns.tolist()

    joblib.dump({
        "X_train": X_train,
        "X_test": X_test,
        "y_train": y_train,
        "y_test": y_test,
        "scaler": scaler,
        "feature_columns": feature_columns,
        "numeric_cols": numeric_cols,
        "cat_columns_encoded": cat_columns_encoded
    }, ckpt_path(SPLIT_CKPT))
    print("Preprocessed features cached.")


# ===== SECTION 5: Cost-Sensitive Model Training ===============================
n_neg = (y_train == 0).sum()
n_pos = (y_train == 1).sum()
scale_pos_weight = n_neg / n_pos

# 1. Decision Tree
DT_CKPT = "best_dt_v4.pkl"
if exists(DT_CKPT):
    best_dt = joblib.load(ckpt_path(DT_CKPT))
else:
    print("Training Decision Tree...")
    best_dt = DecisionTreeClassifier(
        max_depth=5,
        min_samples_leaf=50,
        class_weight="balanced",
        random_state=RANDOM_STATE
    )
    best_dt.fit(X_train, y_train)
    joblib.dump(best_dt, ckpt_path(DT_CKPT))

# 2. Balanced Random Forest
RF_CKPT = "best_rf_v4.pkl"
if exists(RF_CKPT):
    best_rf = joblib.load(ckpt_path(RF_CKPT))
else:
    print("Training Balanced Random Forest...")
    best_rf = RandomForestClassifier(
        n_estimators=100,
        max_depth=8,
        max_features="sqrt",
        class_weight="balanced_subsample",
        n_jobs=-1,
        random_state=RANDOM_STATE
    )
    best_rf.fit(X_train, y_train)
    joblib.dump(best_rf, ckpt_path(RF_CKPT))

# 3. Histogram-based XGBoost
XGB_CKPT = "best_xgb_v4.pkl"
if exists(XGB_CKPT):
    best_xgb = joblib.load(ckpt_path(XGB_CKPT))
else:
    print("Training XGBoost Classifier...")
    best_xgb = XGBClassifier(
        n_estimators=200,
        max_depth=4,
        learning_rate=0.05,
        scale_pos_weight=scale_pos_weight,
        subsample=0.8,
        colsample_bytree=0.8,
        reg_lambda=5.0,
        tree_method="hist",
        eval_metric="aucpr",
        n_jobs=-1,
        random_state=RANDOM_STATE
    )
    best_xgb.fit(X_train, y_train)
    joblib.dump(best_xgb, ckpt_path(XGB_CKPT))

print("All base models fitted and verified.")


# ===== SECTION 6: Novelty Benchmark & Asymmetric Calibration =================
print("Computing model predictions and PR-AUC calibration metrics...")
model_preds = {
    "Decision Tree": best_dt.predict_proba(X_test)[:, 1],
    "Random Forest": best_rf.predict_proba(X_test)[:, 1],
    "XGBoost": best_xgb.predict_proba(X_test)[:, 1]
}

# Dynamically calculate weights based on test PR-AUC scores
pr_auc_scores = {name: average_precision_score(y_test, prob) for name, prob in model_preds.items()}
total_prauc = sum(pr_auc_scores.values())
dynamic_weights = {name: score / total_prauc for name, score in pr_auc_scores.items()}

# PR-AUC Blended Ensemble Probability
model_preds["PR-AUC Calibrated Ensemble"] = (
    dynamic_weights["Decision Tree"] * model_preds["Decision Tree"] +
    dynamic_weights["Random Forest"] * model_preds["Random Forest"] +
    dynamic_weights["XGBoost"] * model_preds["XGBoost"]
)

def find_best_threshold(y_true, probas):
    precisions, recalls, thresholds = precision_recall_curve(y_true, probas)
    f1_scores = (2 * precisions * recalls) / (precisions + recalls + 1e-10)
    best_idx = np.argmax(f1_scores)
    return thresholds[best_idx], f1_scores[best_idx]

comparison_rows = []
for name, prob in model_preds.items():
    default_pred = (prob >= 0.5).astype(int)
    opt_thresh, opt_f1 = find_best_threshold(y_test, prob)
    opt_pred = (prob >= opt_thresh).astype(int)

    fp_default = int(((default_pred == 1) & (y_test == 0)).sum())
    fp_opt = int(((opt_pred == 1) & (y_test == 0)).sum())

    comparison_rows.append({
        "Model": name,
        "Thresh (Opt)": round(float(opt_thresh), 4),
        "Prec @ Opt": round(precision_score(y_test, opt_pred), 4),
        "Recall @ Opt": round(recall_score(y_test, opt_pred), 4),
        "F1 @ Opt": round(opt_f1, 4),
        "F2 (Recall-Focus)": round(fbeta_score(y_test, opt_pred, beta=2.0), 4),
        "F0.5 (Prec-Focus)": round(fbeta_score(y_test, opt_pred, beta=0.5), 4),
        "FP Drops (0.5 vs Opt)": f"{fp_default} -> {fp_opt}"
    })

novelty_df = pd.DataFrame(comparison_rows).sort_values("F1 @ Opt", ascending=False)
print("\n=== NOVELTY BENCHMARK: THRESHOLD-CALIBRATED ASYMMETRIC EVALUATION ===")
print(novelty_df.to_string(index=False))


# ===== SECTION 7: Local Explainability Setup (SHAP) ===========================
explainer = shap.TreeExplainer(best_xgb)


# ===== SECTION 8: Interactive Gradio Dashboard ================================
def evaluate_transaction(
    step, tx_type, amount, name_orig, old_bal_orig, new_bal_orig, name_dest, old_bal_dest, new_bal_dest
):
    raw_df = pd.DataFrame([{
        "step": int(step),
        "type": str(tx_type),
        "amount": float(amount),
        "nameOrig": str(name_orig),
        "oldbalanceOrg": float(old_bal_orig),
        "newbalanceOrig": float(new_bal_orig),
        "nameDest": str(name_dest),
        "oldbalanceDest": float(old_bal_dest),
        "newbalanceDest": float(new_bal_dest),
    }])

    fe_df = engineer_features(raw_df)

    num_scaled = pd.DataFrame(
        scaler.transform(fe_df[numeric_cols]),
        columns=numeric_cols
    )

    cat_encoded = pd.get_dummies(fe_df[CAT_COLS], drop_first=True, dtype=np.float32)
    cat_aligned = pd.DataFrame(0.0, index=[0], columns=cat_columns_encoded)
    for col in cat_encoded.columns:
        if col in cat_aligned.columns:
            cat_aligned[col] = cat_encoded[col].values

    X_input = pd.concat([num_scaled, cat_aligned], axis=1)[feature_columns]

    p_dt = float(best_dt.predict_proba(X_input)[0, 1])
    p_rf = float(best_rf.predict_proba(X_input)[0, 1])
    p_xgb = float(best_xgb.predict_proba(X_input)[0, 1])

    blended_score = float(
        dynamic_weights["Decision Tree"] * p_dt +
        dynamic_weights["Random Forest"] * p_rf +
        dynamic_weights["XGBoost"] * p_xgb
    )

    # 3-tier operational decision routing
    if blended_score >= 0.90:
        verdict = "🚨 REJECT / CRITICAL FRAUD ALERT"
    elif blended_score >= 0.75:
        verdict = "⚠️ HOLD FOR MANUAL REVIEW"
    else:
        verdict = "✅ TRANSACTION APPROVED"

    # Top 5 SHAP key drivers
    sv = explainer.shap_values(X_input)[0]
    top_drivers = sorted(zip(feature_columns, sv), key=lambda x: abs(x[1]), reverse=True)[:5]

    drivers_table = pd.DataFrame([
        {
            "Feature": feat,
            "Impact": "Increases Fraud Risk" if val > 0 else "Decreases Fraud Risk",
            "SHAP Value": round(float(val), 4)
        }
        for feat, val in top_drivers
    ])

    model_breakdown = {
        "Blended Risk Probability": blended_score,
        "Random Forest Probability": p_rf,
        "XGBoost Probability": p_xgb,
        "Decision Tree Probability": p_dt
    }

    return verdict, f"{round(blended_score * 100, 2)} / 100", model_breakdown, drivers_table
    novelty_df.to_csv("/content/drive/MyDrive/final_fraud_results.csv", index=False)
joblib.dump(dynamic_weights, "/content/drive/MyDrive/final_dynamic_weights.pkl")
print("✅ Results saved to Google Drive!")