# -*- coding: utf-8 -*-
"""review02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AAWVKSgqLQAL6bVgkltViFYm1tvlEV2O
"""

# ============================================================
# Fraud Detection - GridSearch-Optimized Models + Hard Voting Ensemble
#
# Three classifiers (Decision Tree, Random Forest, XGBoost) tuned via
# GridSearchCV, then combined into a Hard Voting ensemble. The core
# imbalance-handling choices (class_weight='balanced' for RF,
# scale_pos_weight for XGBoost) are kept fixed since those are
# deliberate design decisions, not something to search over; the grid
# tunes capacity/regularization parameters (depth, leaf size, learning
# rate, subsampling, etc.) around them.
#
# All models and grid-search results are cached to Google Drive —
# rerunning this script will not retrain anything already saved.
# ============================================================

# Install packages (Run once in Google Colab)
!pip install -q xgboost imbalanced-learn

# ============================================================
# Import Libraries
# ============================================================

import pandas as pd
import numpy as np
import joblib
import os

from google.colab import drive
drive.mount('/content/drive')

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from xgboost import XGBClassifier

from imblearn.over_sampling import SMOTE

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    make_scorer,
    fbeta_score,
    classification_report,
    confusion_matrix
)

# ============================================================
# Model caching — saves every trained model / grid-search result
# to Google Drive. Includes a feature-schema check: a cached model
# trained on a different feature set than the current run produces
# is discarded and refit automatically, rather than crashing at
# predict() time with a stale, mismatched model.
# ============================================================

MODEL_DIR = "/content/drive/MyDrive/cvel_model_cache"
os.makedirs(MODEL_DIR, exist_ok=True)

def load_or_fit(path, fit_fn, expected_n_features=None):
    if os.path.exists(path):
        cached = joblib.load(path)
        if expected_n_features is not None and hasattr(cached, "n_features_in_"):
            if cached.n_features_in_ != expected_n_features:
                print(f"  [STALE CACHE] {os.path.basename(path)} was trained on "
                      f"{cached.n_features_in_} features, current run has "
                      f"{expected_n_features}. Discarding and refitting...")
                os.remove(path)
            else:
                print(f"  [CACHE HIT] Loaded {os.path.basename(path)}")
                return cached
        else:
            print(f"  [CACHE HIT] Loaded {os.path.basename(path)}")
            return cached

    print(f"  [CACHE MISS] Fitting and saving {os.path.basename(path)}...")
    result = fit_fn()
    joblib.dump(result, path)
    return result

# ============================================================
# Load Dataset
# ============================================================

df = pd.read_csv(
    "/content/drive/MyDrive/PS_20174392719_1491204439457_log.csv"
)

print(df.head())
print(df.shape)

# ============================================================
# Feature Engineering
# ============================================================

df["type_variant"] = (
    df["nameOrig"].str[0] +
    df["nameDest"].str[0]
)

df.drop(["nameOrig", "nameDest"], axis=1, inplace=True)

df = pd.get_dummies(
    df,
    columns=["type", "type_variant"],
    drop_first=True
)

X = df.drop(columns=["isFraud"], errors="ignore")
y = df["isFraud"]

if "isFlaggedFraud" in X.columns:
    X = X.drop(columns=["isFlaggedFraud"])

# ============================================================
# Train-Test Split
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42, stratify=y
)

# ============================================================
# Feature Scaling
# ============================================================

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# ============================================================
# Apply SMOTE ONLY on Training Data
# ============================================================

smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

print("\nBefore SMOTE")
print(y_train.value_counts())
print("\nAfter SMOTE")
print(pd.Series(y_train_smote).value_counts())

scale_pos_weight = y_train.value_counts()[0] / y_train.value_counts()[1]
n_features = X_train_smote.shape[1]

# ============================================================
# Evaluation helper (accuracy + fraud-class precision/recall/F1)
# ============================================================

results = []

def evaluate(name, model_or_preds, X_te=None, is_preds=False):
    y_pred = model_or_preds if is_preds else model_or_preds.predict(X_te)

    accuracy = accuracy_score(y_test, y_pred)
    precision_1 = precision_score(y_test, y_pred, pos_label=1)
    recall_1 = recall_score(y_test, y_pred, pos_label=1)
    f1_1 = f1_score(y_test, y_pred, pos_label=1)

    print("\n" + "=" * 70)
    print(name)
    print("=" * 70)
    print(f"Accuracy : {accuracy * 100:.2f}%")
    print(f"Class 1 (fraud) -> Precision: {precision_1:.3f} | "
          f"Recall: {recall_1:.3f} | F1: {f1_1:.3f}")
    print(classification_report(y_test, y_pred))
    print(confusion_matrix(y_test, y_pred))

    results.append({
        "Model": name,
        "Accuracy (%)": round(accuracy * 100, 2),
        "Precision (Class 1)": round(precision_1, 3),
        "Recall (Class 1)": round(recall_1, 3),
        "F1 (Class 1)": round(f1_1, 3)
    })
    return y_pred

# ============================================================
# GridSearchCV setup
# ============================================================

fbeta_scorer = make_scorer(fbeta_score, beta=1.0, pos_label=1)  # F1 on fraud class

# Search on a stratified subsample — PaySim + SMOTE produces a training
# set of several million rows, and a full grid search at that scale is
# impractical. Best params are refit on the full SMOTE-resampled set.
SEARCH_SAMPLE_SIZE = 200_000
if len(X_train_smote) > SEARCH_SAMPLE_SIZE:
    X_search, _, y_search, _ = train_test_split(
        X_train_smote, y_train_smote,
        train_size=SEARCH_SAMPLE_SIZE,
        stratify=y_train_smote,
        random_state=42
    )
else:
    X_search, y_search = X_train_smote, y_train_smote

print(f"\nGrid search subsample size: {len(X_search)} rows")

# --- Decision Tree ---
dt_grid = {
    "criterion": ["entropy", "gini"],
    "max_depth": [8, 12, 16, None],
    "min_samples_split": [5, 10, 20],
    "min_samples_leaf": [2, 4, 8],
    "class_weight": ["balanced", None]
}
dt_best_params = load_or_fit(
    os.path.join(MODEL_DIR, "gs_dt_bestparams.joblib"),
    lambda: GridSearchCV(
        DecisionTreeClassifier(random_state=42),
        dt_grid, cv=3, scoring=fbeta_scorer, n_jobs=-1, verbose=1
    ).fit(X_search, y_search).best_params_
)
print("\nBest Decision Tree params:", dt_best_params)

tuned_dt = load_or_fit(
    os.path.join(MODEL_DIR, "gs_tuned_dt.joblib"),
    lambda: DecisionTreeClassifier(random_state=42, **dt_best_params).fit(X_train_smote, y_train_smote),
    expected_n_features=n_features
)

# --- Random Forest (class_weight='balanced' fixed) ---
rf_grid = {
    "n_estimators": [150, 200, 300],
    "max_depth": [10, 15, 20, None],
    "min_samples_split": [5, 10],
    "min_samples_leaf": [2, 4]
}
rf_best_params = load_or_fit(
    os.path.join(MODEL_DIR, "gs_rf_bestparams.joblib"),
    lambda: GridSearchCV(
        RandomForestClassifier(random_state=42, n_jobs=-1, class_weight="balanced"),
        rf_grid, cv=3, scoring=fbeta_scorer, n_jobs=-1, verbose=1
    ).fit(X_search, y_search).best_params_
)
print("\nBest Random Forest params:", rf_best_params)

tuned_rf = load_or_fit(
    os.path.join(MODEL_DIR, "gs_tuned_rf.joblib"),
    lambda: RandomForestClassifier(
        random_state=42, n_jobs=-1, class_weight="balanced", **rf_best_params
    ).fit(X_train_smote, y_train_smote),
    expected_n_features=n_features
)

# --- XGBoost (scale_pos_weight fixed) ---
xgb_grid = {
    "n_estimators": [150, 200, 300],
    "max_depth": [4, 6, 8],
    "learning_rate": [0.05, 0.1, 0.2],
    "subsample": [0.7, 0.8, 1.0],
    "colsample_bytree": [0.7, 0.8, 1.0]
}
xgb_best_params = load_or_fit(
    os.path.join(MODEL_DIR, "gs_xgb_bestparams.joblib"),
    lambda: GridSearchCV(
        XGBClassifier(random_state=42, eval_metric="logloss",
                      scale_pos_weight=scale_pos_weight),
        xgb_grid, cv=3, scoring=fbeta_scorer, n_jobs=-1, verbose=1
    ).fit(X_search, y_search).best_params_
)
print("\nBest XGBoost params:", xgb_best_params)

tuned_xgb = load_or_fit(
    os.path.join(MODEL_DIR, "gs_tuned_xgb.joblib"),
    lambda: XGBClassifier(
        random_state=42, eval_metric="logloss", scale_pos_weight=scale_pos_weight,
        **xgb_best_params
    ).fit(X_train_smote, y_train_smote),
    expected_n_features=n_features
)

# ============================================================
# Evaluate optimized models
# ============================================================

pred_dt = evaluate("Optimized Decision Tree (GridSearch)", tuned_dt, X_test)
pred_rf = evaluate("Balanced Random Forest (GridSearch)", tuned_rf, X_test)
pred_xgb = evaluate("Weighted XGBoost (GridSearch)", tuned_xgb, X_test)

# ============================================================
# Hard Voting Ensemble
# ============================================================

stacked = np.vstack([pred_dt, pred_rf, pred_xgb]).astype(int)

def majority_vote(col):
    counts = np.bincount(col, minlength=2)
    if counts[0] == counts[1]:
        return np.random.choice([0, 1])
    return int(np.argmax(counts))

ensemble_pred = np.apply_along_axis(majority_vote, axis=0, arr=stacked)
evaluate("Hard Voting Ensemble (GridSearch-Optimized)", ensemble_pred, is_preds=True)

# ============================================================
# Comparison Table
# ============================================================

results_df = pd.DataFrame(results)
results_df = results_df.sort_values(by="F1 (Class 1)", ascending=False)

print("\n\n")
print("=" * 70)
print("GridSearch-Optimized Model Comparison")
print("=" * 70)
print(results_df.to_string(index=False))

results_df.to_csv(
    "/content/drive/MyDrive/gridsearch_optimized_results.csv", index=False
)
print("\nSaved to /content/drive/MyDrive/gridsearch_optimized_results.csv")